services:
  freshrss:
    image: freshrss/freshrss:1.26.3
    container_name: freshrss_vuln
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - TZ=UTC
      - CRON_MIN=0,30
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions

volumes:
  freshrss_data:
  freshrss_extensions:
