services:
  getsimple:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - getsimple_data:/var/www/html/data
      - getsimple_backups:/var/www/html/backups

volumes:
  getsimple_data:
  getsimple_backups:
