version: '2'
networks:
  xwiki-net:
    driver: bridge

services:
  web:
    image: xwiki:16.10.0-mysql-tomcat
    container_name: xwiki-web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_DATABASE=xwiki
      - DB_HOST=db
    volumes:
      - xwiki-data:/usr/local/xwiki
    networks:
      - xwiki-net

  db:
    image: mysql:8.0
    container_name: xwiki-db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./build_depend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=xwiki
      - MYSQL_USER=xwiki
      - MYSQL_PASSWORD=xwiki
      - MYSQL_DATABASE=xwiki
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
      - "--explicit-defaults-for-timestamp=1"
      - "--default-authentication-plugin=mysql_native_password"
    networks:
      - xwiki-net

volumes:
  mysql-data: {}
  xwiki-data: {}
