version: '3'
services:
  grav:
    image: linuxserver/grav:version-1.7.46
    container_name: grav-cve-2025-66295
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - grav_config:/config
    ports:
      - 8088:80
      - 8443:443
    restart: unless-stopped

volumes:
  grav_config:
