version: '3.8'

services:
  engineercms:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    container_name: cve-2025-44831-engineercms
    ports:
      - "8081:80"
    restart: unless-stopped
