version: '3'
services:
  pluxml:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    container_name: pluxml-cve-2025-57567
    ports:
      - "8089:80"
    volumes:
      - pluxml_data:/var/www/html/data

volumes:
  pluxml_data:
