services:
  memos:
    image: neosmemo/memos:0.24.3
    container_name: memos-50738
    ports:
      - "5230:5230"
    volumes:
      - memos-data:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_ADDR=0.0.0.0
      - MEMOS_PORT=5230

volumes:
  memos-data:
