services:
  traefik:
    image: traefik:v2.11.24
    container_name: traefik-vuln
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend:
    image: nginx:alpine
    container_name: backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public-only.rule=PathPrefix(`/public`)"
      - "traefik.http.routers.public-only.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
    volumes:
      - ./build_depend:/usr/share/nginx/html
