version: "3"
services:
  appsmith:
    image: appsmith/appsmith-ce:v1.47
    container_name: appsmith-cve-2024-55964
    ports:
      - "18181:80"
      - "18443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
