debug = true

[http]
port = 3000

[jwt]
key = "secret"
algo = "HS256"

[auth]
enabled = false
type = "body"
encrypt = "MD5"
table = "prest_users"
username = "username"
password = "password"

[pg]
host = "postgres"
user = "prest"
pass = "prest"
port = 5432
database = "db001"
single = true

[ssl]
mode = "disable"

[expose]
enabled = true
databases = true
schemas = true
tables = true
