version: '3.8'

services:
  imagemagick-web:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    container_name: cve-2025-57807
    ports:
      - "8888:80"
    volumes:
      - ./uploads:/var/www/html/uploads
