version: "3.8"

services:
  aim:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    ports:
      - "43800:43800"
      - "53800:53800"
    volumes:
      - aim_data:/opt/aim
    command: ["sh", "-c", "aim up --host 0.0.0.0 --port 43800 & aim server --host 0.0.0.0 --port 53800 && wait"]

volumes:
  aim_data:
