version: "3.8"

services:
  readarr:
    image: linuxserver/readarr:develop-0.4.15.2787-ls152
    container_name: readarr-vuln
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./build_depend/config:/config
      - ./build_depend/books:/books
      - ./build_depend/downloads:/downloads
    ports:
      - "8787:8787"
    restart: unless-stopped
