services:
  db_recipes:
    restart: always
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=djangodb
      - POSTGRES_PASSWORD=djangodb
      - POSTGRES_DB=djangodb

  web_recipes:
    restart: always
    image: vabene1111/recipes:1.5.23
    ports:
      - "9080:8080"
    environment:
      - SECRET_KEY=vuln_test_secret_key_12345
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangodb
      - POSTGRES_PASSWORD=djangodb
      - POSTGRES_DB=djangodb
      - DEBUG=1
      - ALLOWED_HOSTS=*
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
