version: '3'
services:
  xwiki:
    image: xwiki:16.4.0-postgres-tomcat
    container_name: xwiki-vuln
    depends_on:
      - db
    ports:
      - "18080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=db
      - DB_DATABASE=xwiki
    volumes:
      - xwiki-data:/usr/local/xwiki
    networks:
      - xwiki-net

  db:
    image: postgres:15
    container_name: xwiki-db
    environment:
      - POSTGRES_USER=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - xwiki-net

volumes:
  xwiki-data:
  postgres-data:

networks:
  xwiki-net:
    driver: bridge
