services:
  navidrome:
    image: deluan/navidrome:0.55.2
    container_name: navidrome-vuln
    ports:
      - "4533:4533"
    environment:
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - ./build_depend/data:/data
      - ./build_depend/music:/music:ro
    restart: unless-stopped
