version: '3.8'

services:
  flatpress:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    container_name: flatpress-cve-2024-4023
    ports:
      - "8081:80"
    restart: unless-stopped
