version: '3'
services:
  icescrum:
    build: ./build_depend
    ports:
      - "8080:8080"
    volumes:
      - icescrum-logs:/root/logs/
    environment:
      - JAVA_OPTS=-Xmx1024m -Dicescrum.log.dir=/root/logs/ -Dicescrum.environment=docker

volumes:
  icescrum-logs:
