name: cve-2025-55010

services:
  kanboard:
    image: kanboard/kanboard:v1.2.46
    container_name: kanboard-vuln
    ports:
      - "8080:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
    environment:
      - DATABASE_URL=sqlite://data/db.sqlite

volumes:
  kanboard_data:
  kanboard_plugins:
