version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    restart: always

  web:
    image: xwiki:16.4.0-postgres-tomcat
    container_name: xwiki-web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_HOST=db
      - DB_DATABASE=xwiki
      - DB_DRIVER=org.postgresql.Driver
      - DB_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
