services:
  bentoml-vulnerable:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - vuln_net

  internal-service:
    image: nginx:alpine
    volumes:
      - ./build_depend/internal_data:/usr/share/nginx/html:ro
    networks:
      - vuln_net

networks:
  vuln_net:
    driver: bridge
