services:
  wekandb:
    image: mongo:6
    container_name: wekan-mongo-65779
    ports:
      - "27017:27017"
    networks:
      - wekan-tier
    volumes:
      - wekan-db-data:/data/db

  wekan:
    image: wekanteam/wekan:v8.15
    container_name: wekan-app-65779
    ports:
      - "8085:8080"
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost:8085
      - WITH_API=true
    depends_on:
      - wekandb
    networks:
      - wekan-tier

networks:
  wekan-tier:
    driver: bridge

volumes:
  wekan-db-data:
