version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dzzoffice
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    ports:
      - "8787:80"
    depends_on:
      - db
    volumes:
      - dzz_data:/var/www/html/data
      - dzz_config:/var/www/html/config

volumes:
  db_data:
  dzz_data:
  dzz_config:
