services:
  filerise:
    image: error311/filerise-docker:v2.5.2
    container_name: filerise-vuln
    restart: always
    ports:
      - "8081:80"
    environment:
      TIMEZONE: "UTC"
      TOTAL_UPLOAD_SIZE: "10G"
      SECURE: "false"
      PERSISTENT_TOKENS_KEY: "vuln_test_key_12345"
      SCAN_ON_START: "true"
      CHOWN_ON_START: "true"
    volumes:
      - filerise_uploads:/var/www/uploads
      - filerise_users:/var/www/users
      - filerise_metadata:/var/www/metadata

volumes:
  filerise_uploads:
  filerise_users:
  filerise_metadata:
