version: '3'
services:
  shopxo:
    build: ./build_depend
    container_name: shopxo_cve_2025_26325
    ports:
      - "18088:80"
    depends_on:
      - mysql
    networks:
      - shopxo_net

  mysql:
    image: mysql:5.7
    container_name: shopxo_mysql_cve_2025_26325
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: shopxo
    networks:
      - shopxo_net

networks:
  shopxo_net:
