services:
  database:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: churchcrm
      MYSQL_USER: churchcrm
      MYSQL_PASSWORD: churchcrm123
    volumes:
      - ./build_depend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10

  churchcrm:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    ports:
      - "8086:80"
    environment:
      MYSQL_DB_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: churchcrm
      MYSQL_USER: churchcrm
      MYSQL_PASSWORD: churchcrm123
    depends_on:
      database:
        condition: service_healthy
