spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dataease?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dataease
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 30000

dataease:
  init_password: DataEase123456
  login_timeout: 480

logger:
  level: INFO

engine_mode: simple
