version: '3.8'

services:
  engineercms:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    container_name: engineercms-vuln
    ports:
      - "8092:8081"
    restart: unless-stopped
