version: '3.8'

services:
  yii2-vuln:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - yii2-net
    restart: unless-stopped

networks:
  yii2-net:
    driver: bridge
