version: '3.8'

services:
  vulnerable-curl:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    container_name: cve-2025-0725-curl
    networks:
      - vuln-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  vuln-net:
    driver: bridge
