version: '3.8'

services:
  haxcms:
    build:
      context: ./build_depend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
