x-db-env: &db-env
  PGHOST: plane-db
  PGDATABASE: plane
  POSTGRES_USER: plane
  POSTGRES_PASSWORD: plane
  POSTGRES_DB: plane
  POSTGRES_PORT: "5432"
  PGDATA: /var/lib/postgresql/data

x-redis-env: &redis-env
  REDIS_HOST: plane-redis
  REDIS_PORT: "6379"
  REDIS_URL: redis://plane-redis:6379/

x-minio-env: &minio-env
  MINIO_ROOT_USER: access-key
  MINIO_ROOT_PASSWORD: secret-key

x-aws-s3-env: &aws-s3-env
  AWS_REGION: ""
  AWS_ACCESS_KEY_ID: access-key
  AWS_SECRET_ACCESS_KEY: secret-key
  AWS_S3_ENDPOINT_URL: http://plane-minio:9000
  AWS_S3_BUCKET_NAME: uploads

x-proxy-env: &proxy-env
  APP_DOMAIN: localhost
  FILE_SIZE_LIMIT: "5242880"
  LISTEN_HTTP_PORT: "80"
  LISTEN_HTTPS_PORT: "443"
  BUCKET_NAME: uploads
  SITE_ADDRESS: ":80"

x-mq-env: &mq-env
  RABBITMQ_HOST: plane-mq
  RABBITMQ_PORT: "5672"
  RABBITMQ_DEFAULT_USER: plane
  RABBITMQ_DEFAULT_PASS: plane
  RABBITMQ_DEFAULT_VHOST: plane
  RABBITMQ_VHOST: plane

x-live-env: &live-env
  API_BASE_URL: http://api:8000

x-app-env: &app-env
  WEB_URL: http://localhost:8080
  DEBUG: "0"
  CORS_ALLOWED_ORIGINS: http://localhost:8080
  GUNICORN_WORKERS: "1"
  USE_MINIO: "1"
  DATABASE_URL: postgresql://plane:plane@plane-db/plane
  SECRET_KEY: 60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5
  AMQP_URL: amqp://plane:plane@plane-mq:5672/plane
  API_KEY_RATE_LIMIT: 60/minute
  MINIO_ENDPOINT_SSL: "0"

services:
  web:
    image: makeplane/plane-frontend:v1.0.0
    container_name: plane-web
    restart: always
    depends_on:
      - api
      - worker

  space:
    image: makeplane/plane-space:v1.0.0
    container_name: plane-space
    restart: always
    depends_on:
      - api
      - worker
      - web

  admin:
    image: makeplane/plane-admin:v1.0.0
    container_name: plane-admin
    restart: always
    depends_on:
      - api
      - web

  live:
    image: makeplane/plane-live:v1.0.0
    container_name: plane-live
    environment:
      <<: [*live-env]
    restart: always
    depends_on:
      - api
      - web

  api:
    image: makeplane/plane-backend:v1.0.0
    container_name: plane-api
    command: ./bin/docker-entrypoint-api.sh
    restart: always
    volumes:
      - logs_api:/code/plane/logs
    environment:
      <<: [*app-env, *db-env, *redis-env, *minio-env, *aws-s3-env, *proxy-env]
    depends_on:
      - plane-db
      - plane-redis
      - plane-mq

  worker:
    image: makeplane/plane-backend:v1.0.0
    container_name: plane-worker
    command: ./bin/docker-entrypoint-worker.sh
    restart: always
    volumes:
      - logs_worker:/code/plane/logs
    environment:
      <<: [*app-env, *db-env, *redis-env, *minio-env, *aws-s3-env, *proxy-env]
    depends_on:
      - api
      - plane-db
      - plane-redis
      - plane-mq

  beat-worker:
    image: makeplane/plane-backend:v1.0.0
    container_name: plane-beat-worker
    command: ./bin/docker-entrypoint-beat.sh
    restart: always
    volumes:
      - logs_beat-worker:/code/plane/logs
    environment:
      <<: [*app-env, *db-env, *redis-env, *minio-env, *aws-s3-env, *proxy-env]
    depends_on:
      - api
      - plane-db
      - plane-redis
      - plane-mq

  migrator:
    image: makeplane/plane-backend:v1.0.0
    container_name: plane-migrator
    command: ./bin/docker-entrypoint-migrator.sh
    restart: "no"
    volumes:
      - logs_migrator:/code/plane/logs
    environment:
      <<: [*app-env, *db-env, *redis-env, *minio-env, *aws-s3-env, *proxy-env]
    depends_on:
      - plane-db
      - plane-redis

  plane-db:
    image: postgres:15.7-alpine
    container_name: plane-db
    command: postgres -c 'max_connections=1000'
    restart: always
    environment:
      <<: *db-env
    volumes:
      - pgdata:/var/lib/postgresql/data

  plane-redis:
    image: valkey/valkey:7.2.5-alpine
    container_name: plane-redis
    restart: always
    volumes:
      - redisdata:/data

  plane-mq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: plane-mq
    restart: always
    environment:
      <<: *mq-env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  plane-minio:
    image: minio/minio:latest
    container_name: plane-minio
    command: server /export --console-address ":9090"
    restart: always
    environment:
      <<: *minio-env
    volumes:
      - uploads:/export

  proxy:
    image: makeplane/plane-proxy:v1.0.0
    container_name: plane-proxy
    restart: always
    environment:
      <<: *proxy-env
    ports:
      - "8080:80"
    depends_on:
      - web
      - api
      - space
      - admin
      - live

volumes:
  pgdata:
  redisdata:
  uploads:
  logs_api:
  logs_worker:
  logs_beat-worker:
  logs_migrator:
  rabbitmq_data:
